name: atlas
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0


  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_ui_auth: ^3.0.1
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/burger1.png
    - assets/burgerLogin.png
    - assets/icon-burger.png
    - assets/icon-pizza.png
    - assets/icon-drink.png
    - assets/icon-dessert.png
    - assets/pizza1.png